### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when accessing /admin

### ISSUE THREAD

**Issue by GuimaraesJC** [digitalinteraction/vercel-netlify-cms-github#11]
I'm trying to configure NetlifyCMS on my **Next.js** application. After following all steps mentioned on the README.md, I'm trying to access [https://guimaraes.tech/admin](https://guimaraes.tech/admin) but I keep receiving this error:

![image1](https://user-images.githubusercontent.com/53412177/223181382-ee8904a2-e194-4257-a1af-f7c4609039df.jpg)

This is my configuration on Github:

![image4](https://user-images.githubusercontent.com/53412177/223182018-012df1b3-e130-449a-b8a0-57cd897dad8f.jpg)

I have the files `auth.ts` and `callback.ts` as described on documentation:

![image5](https://user-images.githubusercontent.com/53412177/223182372-e50e41dd-ee7d-46ab-b4b2-d1e18f15784e.jpg)

I'm also using the `vercel.json` file with the following content:

```json
{
  "trailingSlash": true
}
```

This domain [https://guimaraes.tech](https://guimaraes.tech) was bought on GoDaddy, and this is the current configuration:

![image2](https://user-images.githubusercontent.com/53412177/223183364-41531878-3981-4c09-b781-36021d027f24.jpg)

And Vercel recognizes it as correct:

![image6](https://user-images.githubusercontent.com/53412177/223183612-29728490-d9b6-41fc-bbab-bb8841f44f7d.jpg)

Environment variables on Vercel are correct.

I have two of them:

OAUTH_CLIENT_ID
OAUTH_CLIENT_SECRET

And finally, this is my current `public/admin/config.yml` file:

```yml
backend:
  name: github
  branch: main
  repo: GuimaraesJC/guimaraes.tech
  base_url: https://guimaraes.tech/
  auth_endpoint: api/auth

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
...
...
...
```

Can you help me figure out what is the problem here?
