### ISSUE TITLE
No Auth Provider Found

### ISSUE THREAD

**Issue by 28development** [digitalinteraction/vercel-netlify-cms-github#6]
I am still unable to access my netlify backend within my webapp.

I am trying to login like this on production:

```https://myurl.test.io/admin/index.html#/```

After trying to signing I get this Netlify error:

```
No Auth Provider Found
Make sure you've configured the API credentials for Github from the Access part of your Netlify site dashboard.
```

This is my .yaml file:

```
backend:
  name: 'github'
  repo: 28development/myapp
  branch: main
  base_url: 'https://myapp.test.io'
  auth_endpoint: api/auth
  
media_folder: public/img
public_folder: /img
locale: 'de'
local_backend: true
```

Not sure what I am missing.
