### ISSUE TITLE
Can't authenticate to github

### ISSUE THREAD

**Issue by ari-motors-team** [digitalinteraction/vercel-netlify-cms-github#9]
I can't authenticate to github, because I don't have permission to acces to `https://api.github.com/user` (401).
It somehow makes sense to me. I never passed a "Personal access token".
I am using a private repo.

Response:
```json
{
  "message": "Requires authentication",
  "documentation_url": "https://docs.github.com/rest/reference/users#get-the-authenticated-user"
}
```

![image](https://user-images.githubusercontent.com/95754840/153891582-c58f43b4-92da-462d-800b-11454ebbe984.png)

Otherwise I did setup the package as written in the guide and I am able to access the login page. You can check it here.
https://preview-elektrotransporter-vergleich.vercel.app/admin/

Could you please explain, how I am supposed to get the permission to the github api, please?
Could that be a misconfiguration somehow?

files:
![image](https://user-images.githubusercontent.com/95754840/153892567-93673fb8-b0e0-4d99-bae7-59843d1b4673.png)

config.yml
```yml
backend:
  name: github
  repo: ari-motors-team/elektrotransporter-vergleich
  branch: dev
  base_url: https://preview-elektrotransporter-vergleich.vercel.app
  auth_endpoint: api/auth
```

oauth app
![image](https://user-images.githubusercontent.com/95754840/153892781-4cbec151-b530-45a7-9e89-01e5e0297cc0.png)
